SUPPORTMVC.WEB/Controllers/LeftMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SUPPORTMVC.BLL;
using SUPPORTMVC.ENTITIES.DBT;
using SUPPORTMVC.WEB.Filters;

namespace SUPPORTMVC.WEB.Controllers
{
    public class LeftMenuController : Controller
    {
        [Auth]
        public ActionResult SelectedMenuItem(int? id)
        {
            LeftMenuManager lm = new LeftMenuManager();
            LeftMenuItems lmi = lm.GetLeftMenuItemID(id.Value);
            if (lmi.LinkID == 1)
            {
                return RedirectToAction("RequestReg", "Request");
            }
            else if (lmi.LinkID == 2)
            {
                return RedirectToAction("RequestList", "RequestList");
            }
            else if (lmi.LinkID == 3)
            {
                return RedirectToAction("ClosedRequestList", "RequestList");
            }
            else if (lmi.LinkID == 4)
            {
                return RedirectToAction("RequestList", "RequestList");
            }
            else if (lmi.LinkID == 5)
            {
                return RedirectToAction("CompanyReg", "Company");
            }
            else if (lmi.LinkID == 6)
            {
                return RedirectToAction("CompanyList", "Company");
            }
            else if (lmi.LinkID == 7)
            {
                return RedirectToAction("UserReg", "User");
            }
            else if (lmi.LinkID == 8)
            {
                return RedirectToAction("UserList", "User");
            }
            else if (lmi.LinkID == 9)
            {
                return RedirectToAction("UpdateNotes", "Updates");
            }
            else if (lmi.LinkID == 10)
            {
                return RedirectToAction("AddStatus", "AdminRequestExtensions");
            }
            else if (lmi.LinkID == 11)
            {
                return RedirectToAction("AddPriority", "AdminRequestExtensions");
            }
            else if (lmi.LinkID == 12)
            {
                return RedirectToAction("AddType", "AdminRequestExtensions");
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
    }
}

SUPPORTMVC.WEB/Views/Shared/_CommentAnswer.cshtml
@using SUPPORTMVC.ENTITIES.DBT
@model RequestComments

<form>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder">Mesaj Detayı:</label>
        <br />
        <div class="col-lg-10">
            <textarea class="form-control m--font-boldest2" id="m_autosize_1" rows="4" readonly="readonly">@Model.CommentText</textarea>
        </div>
    </div>
    <div class="form-group m-form__group row">
        <div class="col-lg-12">
            <hr />
            <h5 class="modal-title m--margin-left-10" id="exampleModalClose">Cevap Yaz</h5>
            <hr />
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> Cevap Ekle:</label>
        @*<div class="col-lg-9 col-md-9 col-sm-12">
            <textarea class="summernote input-block-level" id="m_summernote_1"></textarea>
        </div>*@
        <div class="col-md-10">
            <textarea class="form-control m--font-boldest2" id="m_autosize_1_kapat" rows="6"></textarea>
        </div>
    </div>
    <hr />
    @Html.HiddenFor(x => Model.CommentID)
    <div class="form-group m-form__group row float-right m--margin-right-65 m--margin-top-5" style="margin-bottom: -1%">
        <button type="button" id="CommentAnswerButton" class="btn btn-info m--font-boldest" style="width: 10rem" onclick="CommentAnswer(this,'CommentAnswer');"> Cevapla </button>
    </div>
</form>

<script src="~/Content/assets/demo/demo12/custom/crud/forms/widgets/autosize.js" type="text/javascript"></script>
<script src="~/Content/assets/demo/demo12/custom/crud/forms/widgets/summernote.js"></script>

SUPPORTMVC.WEB/Views/Shared/_CompanyEdit.cshtml
@using SUPPORTMVC.BLL
@using SUPPORTMVC.ENTITIES.DBT
@model Companies

<form>
    <div class="form-group m-form__group row" style="margin-top: -1rem">
        <div class="col-md-12">
            <span class="m-form__help m--font-danger" style="font-size: 1.1rem"> Firma Kodu ve Firma Adı alanları boş geçilemez!</span>
        </div>
    </div>
    <hr />
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> Firma Kodu:</label>
        <div class="col-md-3">
            <input type="text" class="form-control m-input m--font-boldest2" id="CompanyCode" value="@Model.CompanyCode" />
        </div>
        <label class="col-lg-1 col-form-label m--font-bolder">Domain:</label>
        <div class="col-md-4">
            <input type="text" class="form-control m-input m--font-boldest2" id="CompanyDomain" value="@Model.CompanyDomain" />
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> Firma Adı:</label>
        <div class="col-md-8">
            <input type="text" class="form-control m-input m--font-boldest2" id="CompanyName" value="@Model.CompanyName" />
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder">Yetkili Adı:</label>
        <div class="col-md-3">
            <input type="text" class="form-control m-input m--font-boldest2" id="CompanyAuthName" value="@Model.CompanyAuthName" />
        </div>
        <label class="col-lg-1 col-form-label m--font-bolder">Soyadı:</label>
        <div class="col-md-4">
            <input type="text" class="form-control m-input m--font-boldest2" id="CompanyAuthSurname" value="@Model.CompanyAuthSurname" />
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> E-Mail:</label>
        <div class="col-md-8">
            <input type="text" class="form-control m-input m--font-boldest2" id="CompanyEmail" value="@Model.CompanyEmail" />
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> Ofis No:</label>
        <div class="col-md-3">
            <input type="text" class="form-control m-input m--font-boldest2" id="CompanyOfficePhone" value="@Model.CompanyOfficePhone" />
        </div>
        <label class="col-lg-1 col-form-label m--font-bolder"> CepNo:</label>
        <div class="col-md-4">
            <input type="text" class="form-control m-input m--font-boldest2" id="CompanyMobilePhone" value="@Model.CompanyMobilePhone" />
        </div>
    </div>
    <hr />
    @Html.HiddenFor(x => Model.CompanyID)
    <div class="form-group m-form__group row float-right m--margin-right-65 m--margin-top-5" style="margin-bottom: -1%">
        <button type="button" id="userEditButton" class="btn btn-info m--font-boldest" style="width: 10rem" onclick="EditCompany(this, 'companyEdit');"> Güncelle </button>
    </div>
</form>

SUPPORTMVC.WEB/Views/Shared/_ForgotPassword.cshtml
@using SUPPORTMVC.ENTITIES.DBTO
@model LoginViewModel
@{
    ViewBag.Title = "HBSoft Yazılım&Danışmanlık | Şifremi Unuttum?";
    Layout = null;
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "m-login__form m-form" }))
{
    <div class="form-group m-form__group">
        <input type="text" class="form-control m-input" name="Email" id="txtsifremiunuttummail" placeholder="E-mail" autocomplete="off" />
    </div>
    <div class="m-login__form-action">
        <button type="button" class="btn btn-info m-btn m-btn--pill m-btn--custom m-btn--air m--font-bolder" onclick="ForgotPasswordFunc(this, 'forgotPassword');">Gönder</button>
        <button id="m_login_forget_password_cancel" class="btn btn-outline-info m-btn m-btn--pill m-btn--custom m--font-bolder">İptal</button>
    </div>
}

SUPPORTMVC.WEB/Views/Shared/_HeaderNotificationLayout.cshtml
<li class="m-nav__item m-topbar__notifications m-dropdown m-dropdown--huge m-dropdown--arrow m-dropdown--align-right m-dropdown--mobile-full-width m--bg-fill-light" m-dropdown-toggle="click" m-dropdown-persistent="1">
    <a href="#" class="m-nav__link m-dropdown__toggle" id="m_topbar_notification_icon">
        <span class="m-nav__link-icon">
            <span class="m-nav__link-icon-wrapper">
                <i class="flaticon-alarm"></i>
            </span>
            <span class="m-nav__link-badge m-badge m-badge--danger">3</span>
        </span>
    </a>
    <div class="m-dropdown__wrapper">
        <span class="m-dropdown__arrow m-dropdown__arrow--center"></span>
        <div class="m-dropdown__inner">
            <div class="m-dropdown__header m--align-center">
                <span class="m-dropdown__header-title">HBSoft</span>
                <span class="m-dropdown__header-subtitle">Kullanıcı Bildirimleri</span>
            </div>
            <div class="m-dropdown__body">
                <div class="m-dropdown__content">
                    <ul class="nav nav-tabs m-tabs m-tabs-line m-tabs-line--brand" role="tablist"></ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="topbar_notifications_notifications" role="tabpanel">
                            <div class="m-scrollable" data-scrollable="true" data-height="250" data-mobile-ight="200">
                                <div class="m-list-timeline m-list-timeline--skin-light">
                                    <div class="m-list-timeline__items">
                                        <div class="m-list-timeline__item">
                                            <span class="m-list-timeline__badge -m-list-timeline__badge--state-ccess"></span>
                                            <span class="m-list-timeline__text">Düzenlendi...</span>
                                            <span class="m-list-timeline__time">Şimdi</span>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</li>

SUPPORTMVC.WEB/Views/Shared/_LeftmenuLayout.cshtml
@using SUPPORTMVC.BLL
@using SUPPORTMVC.ENTITIES.DBT

@{
    LeftMenuManager lm = new LeftMenuManager();
    List<LeftMenuItems> topmenuitem = lm.GetLeftMenuItems();
    List<LeftMenuItems> altmenuitem = lm.GetLeftMenuItems();
    UserManager um = new UserManager();
    List<Users> userslist = um.GetUsers();
    
}
@if(Session["User"] != null)
{
    int loggedusername = SUPPORTMVC.COMMON.App.Common.GetUserID().Value;
    int menurole;

<script>
    $(document).ready(function() {
        var expmenu = $("#expandmenu");
        expmenu.click(function() {
            var element = document.getElementsByClassName("m-menu__item  m-menu__item--submenu");
            element.classList.add("m-menu__item  m-menu__item--submenu m-menu__item--expanded");
        });
    })
</script>

<div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-light m-aside-menu--submenu-skin-dark" m-menu-vertical="1" m-menu-crollable="0" m-menu-dropdown-timeout="500">
    <ul class="m-menu__nav ">
        <li class="m-menu__section m-menu__section--first">
            <h4 class="m-menu__section-text">HBSoft</h4>
            <i class="m-menu__section-icon flaticon-more-v2"></i>
        </li>
        <li class="m-menu__item" aria-haspopup="true">
            <a href="@Url.Action("Index","Index")" class="m-menu__link ">
                <span class="m-menu__item-here"></span>
                <i class="m-menu__link-icon flaticon-home-2"></i>
                <span class="m-menu__link-text">Dashboard</span>
            </a>
        </li>

        <!-- Mavi Renk     m-menu__item--expanded   -->


        @foreach (LeftMenuItems lmi in topmenuitem)
        {
            foreach (Users loggeduserinfo in userslist)
            {


                if (loggedusername == loggeduserinfo.UserID)
                {
                    menurole = loggeduserinfo.RoleID;
                    if (menurole >= 4)
                    {
                        if (lmi.TopMenu != 0 && lmi.SubMenu == 0)
                        {
                            <li id="expandmenu" class="m-menu__item  m-menu__item--submenu">
                                <a href="@Url.Action("SelectedMenuItem", "LeftMenu", new {id = @lmi.LinkID})" class="m-menu__link m-menu__toggle">
                                    <span class="m-menu__item-here"></span>
                                    <i class="m-menu__link-icon fa 	fa-square"></i>
                                    <span class="m-menu__link-text">@lmi.MenuName</span>
                                    <i id="menuarrow" class="m-menu__ver-arrow la la-angle-right"></i>
                                </a>
                                <div class="m-menu__submenu ">
                                    @foreach (LeftMenuItems lmia in altmenuitem)
                                    {
                                        <ul class="m-menu__subnav">
                                            @if (lmia.SubMenu == lmi.ItemID && lmia.TopMenu == 0)
                                            {
                                                <li class="m-menu__item  m-menu__item--active" aria-haspopup="true">
                                                    <a href="@Url.Action("SelectedMenuItem", "LeftMenu", new {id = @lmia.LinkID})" class="m-menu__link ">
                                                        <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                                            <span></span>
                                                        </i>
                                                        <span class="m-menu__link-text">@lmia.MenuName</span>
                                                    </a>
                                                </li>
                                            }
                                        </ul>
                                    }
                                </div>
                            </li>
                        }
                    }
                    else if (menurole == 3)
                    {
                        if (lmi.AuthID != 4)
                        {
                            if (lmi.TopMenu != 0 && lmi.SubMenu == 0)
                            {
                                <li id="expandmenu" class="m-menu__item  m-menu__item--submenu">
                                    <a href="@Url.Action("SelectedMenuItem", "LeftMenu", new {id = @lmi.LinkID})" class="m-menu__link m-menu__toggle">
                                        <span class="m-menu__item-here"></span>
                                        <i class="m-menu__link-icon fa 	fa-square"></i>
                                        <span class="m-menu__link-text">@lmi.MenuName</span>
                                        <i id="menuarrow" class="m-menu__ver-arrow la la-angle-right"></i>
                                    </a>
                                    <div class="m-menu__submenu ">
                                        @foreach (LeftMenuItems lmia in altmenuitem)
                                        {
                                            <ul class="m-menu__subnav">
                                                @if (lmia.SubMenu == lmi.ItemID && lmia.TopMenu == 0)
                                                {
                                                    <li class="m-menu__item  m-menu__item--active" aria-haspopup="true">
                                                        <a href="@Url.Action("SelectedMenuItem", "LeftMenu", new {id = @lmia.LinkID})" class="m-menu__link ">
                                                            <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                                                <span></span>
                                                            </i>
                                                            <span class="m-menu__link-text">@lmia.MenuName</span>
                                                        </a>
                                                    </li>
                                                }
                                            </ul>
                                        }
                                    </div>
                                </li>
                            }
                        }
                    }
                    else if (menurole == 2)
                    {

                        if (lmi.TopMenu != 0 && lmi.SubMenu == 0 && lmi.AuthID <= 2)
                        {
                            <li id="expandmenu" class="m-menu__item  m-menu__item--submenu">
                                <a href="@Url.Action("SelectedMenuItem", "LeftMenu", new {id = @lmi.LinkID})" class="m-menu__link m-menu__toggle">
                                    <span class="m-menu__item-here"></span>
                                    @if (lmi.MenuName == "Talep")
                                    {
                                        <i class="m-menu__link-icon flaticon-interface-3"></i>
                                    }
                                    else
                                    {
                                        <i class="m-menu__link-icon flaticon-layers"></i>
                                    }
                                    <span class="m-menu__link-text">@lmi.MenuName</span>
                                    <i id="menuarrow" class="m-menu__ver-arrow la la-angle-right"></i>
                                </a>
                                <div class="m-menu__submenu ">
                                    @foreach (LeftMenuItems lmia in altmenuitem)
                                    {
                                        <ul class="m-menu__subnav">
                                            @if (lmia.SubMenu == lmi.ItemID && lmia.TopMenu == 0 && lmia.AuthID <= 2)
                                            {
                                                <li class="m-menu__item  m-menu__item--active" aria-haspopup="true">
                                                    <a href="@Url.Action("SelectedMenuItem", "LeftMenu", new {id = @lmia.LinkID})" class="m-menu__link ">
                                                        <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                                            <span></span>
                                                        </i>
                                                        <span class="m-menu__link-text">@lmia.MenuName</span>
                                                    </a>
                                                </li>
                                            }
                                        </ul>
                                    }
                                </div>
                            </li>
                        }
                    }
                    else
                    {
                        if (lmi.TopMenu != 0 && lmi.SubMenu == 0 && lmi.AuthID <= 1)
                        {
                            <li id="expandmenu" class="m-menu__item  m-menu__item--submenu">
                                <a href="@Url.Action("SelectedMenuItem", "LeftMenu", new {id = @lmi.LinkID})" class="m-menu__link m-menu__toggle">
                                    <span class="m-menu__item-here"></span>
                                    @if (lmi.MenuName == "Talep")
                                    {
                                        <i class="m-menu__link-icon flaticon-interface-3"></i>
                                    }
                                    else
                                    {
                                        <i class="m-menu__link-icon flaticon-layers"></i>
                                    }
                                    <span class="m-menu__link-text">@lmi.MenuName</span>
                                    <i id="menuarrow" class="m-menu__ver-arrow la la-angle-right"></i>
                                </a>
                                <div class="m-menu__submenu ">
                                    @foreach (LeftMenuItems lmia in altmenuitem)
                                    {
                                        <ul class="m-menu__subnav">
                                            @if (lmia.SubMenu == lmi.ItemID && lmia.TopMenu == 0 && lmia.AuthID <= 1)
                                            {
                                                <li class="m-menu__item  m-menu__item--active" aria-haspopup="true">
                                                    <a href="@Url.Action("SelectedMenuItem", "LeftMenu", new {id = @lmia.LinkID})" class="m-menu__link ">
                                                        <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                                            <span></span>
                                                        </i>
                                                        <span class="m-menu__link-text">@lmia.MenuName</span>
                                                    </a>
                                                </li>
                                            }
                                        </ul>
                                    }
                                </div>
                            </li>
                        }
                    }
                }
            }
        }
    </ul>
</div>
}

SUPPORTMVC.WEB/Views/Shared/_QuickNewUser.cshtml
@using SUPPORTMVC.BLL
@using SUPPORTMVC.ENTITIES.DBTO
@model UserAddModel
<script>
    function sifremigoster() {
        var element = document.getElementById('Password');
        element.type = (element.type == 'password' ? 'text' : 'password');
    }
</script>
<form>
    <div class="form-group m-form__group row" style="margin-top: -1rem">
        <div class="col-md-12">
            <span class="m-form__help m--font-danger" style="font-size: 1.1rem"> <b>1</b>: Standart Kullanıcı, &nbsp; <b>2</b>: Firma Yetkilisi,&nbsp; <b>3</b>: HBS Kullanıcı, &nbsp; <b>4</b>: HBS Yetkilisi</span>
        </div>
    </div>
    <hr />
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> Kullanıcı Adı:</label>
        <div class="col-md-3">
            <input type="text" class="form-control m-input m--font-boldest2" id="Username" />
        </div>
        <label class="col-lg-1 col-form-label m--font-bolder"> Şifre:</label>
        <div class="col-md-4">
            <div class="input-group">
                <input type="password" class="form-control m-input m--font-boldest2" id="Password" name="Password" />
                <div class="input-group-prepend" id="profilsifregoster" onclick="sifremigoster()"><span class="input-group-text"><i class="la la-eye"></i></span></div>
            </div>
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> Adı:</label>
        <div class="col-md-3">
            <input type="text" class="form-control m-input m--font-boldest2" id="UName" />
        </div>
        <label class="col-lg-1 col-form-label m--font-bolder"> Soyadı:</label>
        <div class="col-md-4">
            <input type="text" class="form-control m-input m--font-boldest2" id="USurname" />
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> E-Mail:</label>
        <div class="col-md-8">
            <input type="text" class="form-control m-input m--font-boldest2" id="Email" />
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> Firma:</label>
        <div class="col-md-8">
            <select class="form-control m-select2 m--font-boldest2" id="m_select2_2">
                <option value="0" selected disabled hidden>Firma seçiniz</option>
            </select>
        </div>
    </div>
    <div class="form-group m-form__group row">
        <label class="col-lg-2 col-form-label m--font-bolder"> Kullanıcı Rolü:</label>
        <div class="col-md-2">
            <input type="text" class="form-control m-input m--font-boldest2" id="RoleID" />
        </div>
        <label class="col-lg-2 col-form-label m--font-bolder"> Aktif:</label>
        <div class="col-md-2">
            <span class="m-switch m-switch--lg m-switch--icon">
                <label>
                    <input type="checkbox" class="form-control m-input m--font-boldest2" id="IsActive" checked />
                    <span></span>
                </label>
            </span>
        </div>
    </div>
    <hr />
    <div class="form-group m-form__group row float-right m--margin-right-65 m--margin-top-5" style="margin-bottom: -1%">
        <button type="button" id="userEditButton" class="btn btn-info m--font-boldest" style="width: 10rem" onclick="QuickNewUser(this,'quickuser');"> Oluştur </button>
    </div>
</form>

<script src="~/Content/assets/demo/demo12/custom/crud/forms/widgets/select2.js" type="text/javascript"></script>
<script src="~/TODO_JS/RequestCompanyFilter.js"></script>

SUPPORTMVC.WEB/Views/Shared/_RequestAttendant.cshtml
@using SUPPORTMVC.BLL
@using SUPPORTMVC.ENTITIES.DBT
@model Requests
@{
    RequestManager rm = new RequestManager();
    List<Users> userlist = rm.GetReqUser();
    int loggeduser = SUPPORTMVC.COMMON.App.Common.GetUserID().Value;
    List<AttendantParameter> ap = rm.GetReqAttendantParameter();
}
<script>
    $(document).ready(function() {
        $('#TakeRequestAttendantForm input').on('change',
            function() {
                var y = $('input[name=example_3]:checked', '#TakeRequestAttendantForm').val();

                if (y <= 1) {
                    $('#DivRequestAttendantMe').show();
                    $('#DivRequestAttendantOther').attr("style", "visibility:hidden");
                }
                if (y == 2) {
                    $('#DivRequestAttendantOther').attr("style", "visibility:visible");
                    $('#DivRequestAttendantMe').hide();

                }
            });
    });
</script>


<form id="TakeRequestAttendantForm">
    <div class="form-group m-form__group row">
        <div class="col-lg-12">
            <h6 class="modal-title">Görevlendirilecek Kişiyi Seçiniz</h6>
            <hr />
        </div>

    </div>
    <div class="form-group m-form__group row">
        <div class="col-md-6">
            <div class="m-radio-list">
                <div class="m-form__control m-radio-inline">
                    <label class="m-radio">
                        <input type="radio" id="TakeRequestSelectedValue" name="example_3" value="1" checked>
                        Ben
                        <span></span>
                    </label>
                    @foreach (AttendantParameter atp in ap)
                    {
                        if (!String.IsNullOrEmpty(atp.AttendantDifferentAuth.ToString()) && atp.AttendantDifferentAuth != 0)
                        {
                            <label class="m-radio">
                                <input type="radio" id="TakeRequestSelectedValue2" name="example_3" value="2">
                                Başkası
                                <span></span>
                            </label>
                        }
                    }
                    @foreach (Users usr in userlist)
                    {
                        if (usr.UserID == loggeduser)
                        {
                            if (usr.RoleID >= 4)
                            {
                                <label class="m-radio">
                                    <input type="radio" id="TakeRequestSelectedValue2" name="example_3" value="2">
                                    Başkası
                                    <span></span>
                                </label>
                            }
                        }
                    }

                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="form-group m-form__group row">

        <label class="col-lg-2 col-form-label m--font-bolder">Yetkili Kişiler:</label>
        <div class="col-md-4" id="DivRequestAttendantMe">
            <select class="form-control m-input m--font-boldest2" id="RequestAttendantMe">
                @foreach (Users usr in userlist)
                {
                    if (usr.UserID == loggeduser)
                    {
                        <option value="@usr.UserID" selected>@usr.UName @usr.USurname</option>
                    }
                }

            </select>
        </div>
        <div class="col-md-4" id="DivRequestAttendantOther" style="visibility: hidden">
            <select class="form-control m-input m--font-boldest2" id="RequestAttendantOther">
                <option value="0" selected disabled>Seçiniz</option>
            </select>
        </div>
    </div>
    <hr />
    @Html.HiddenFor(x => Model.RequestID)
    <div class="form-group m-form__group row float-right m--margin-right-65 m--margin-top-5" style="margin-bottom: -1%">
        <button type="button" id="RequestAttendantButton" class="btn btn-info m--font-boldest" style="width: 10rem" onclick="TakeRequestAttendant(this,'TakerequestAttendant');"> Görevlendir </button>
    </div>
</form>

@*<script src="~/TODO_JS/RequestCommentShowField.js"></script>*@
<script src="~/TODO_JS/TakeRequestFilterOwner.js"></script>