SUPPORTMVC.WEB/Controllers/AdminRequestExtensionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SUPPORTMVC.BLL;
using SUPPORTMVC.BLL.Results;
using SUPPORTMVC.COMMON;
using SUPPORTMVC.ENTITIES.DBT;
using SUPPORTMVC.ENTITIES.DBTO;
using SUPPORTMVC.WEB.Filters;

namespace SUPPORTMVC.WEB.Controllers
{
    public class AdminRequestExtensionsController : Controller
    {
        RequestManager rm = new RequestManager();
        [Auth]
        public ActionResult AddStatus()
        {
            int loggeduser = 0;
            if (Session["User"] != null)
            {
                loggeduser = App.Common.GetUserID().Value;
                int userole;
                foreach (Users usr in rm.GetReqUser())
                {
                    if (usr.UserID == loggeduser)
                    {
                        userole = usr.RoleID;
                        if (userole < 3)
                        {
                            return RedirectToAction("Index", "Index");
                        }
                    }
                }
            }
            return View();
        }
        [Auth]
        [HttpPost]
        public ActionResult AddStatus( RequestStatus model)
        {
            if (ModelState.IsValid)
            {
                RequestStatus rs = new RequestStatus();
                if (model.StatusTitle != null)
                {
                    ErrorsResults<RequestStatus> er = rm.AddStatus(model);

                    if (er.Errors.Count > 0)
                    {
                        er.Errors.ForEach(x => ModelState.AddModelError("", x));
                        return View(model);
                    }

                    return View();

                }

            }
            return View(model);
        }
        [Auth]
        public ActionResult AddPriority()
        {
            int loggeduser = 0;
            if (Session["User"] != null)
            {
                loggeduser = App.Common.GetUserID().Value;
                int userole;
                foreach (Users usr in rm.GetReqUser())
                {
                    if (usr.UserID == loggeduser)
                    {
                        userole = usr.RoleID;
                        if (userole < 3)
                        {
                            return RedirectToAction("Index", "Index");
                        }
                    }
                }
            }
            return View();
        }
        [Auth]
        [HttpPost]
        public ActionResult AddPriority(RequestPriority model)
        {
            if (ModelState.IsValid)
            {
                if (model.PriorityTitle != null)
                {
                    ErrorsResults<RequestPriority> er = rm.AddPriority(model);

                    if (er.Errors.Count > 0)
                    {
                        er.Errors.ForEach(x => ModelState.AddModelError("", x));
                        return View(model);
                    }

                    return View();

                }

            }
            return View(model);
        }
        [Auth]
        public ActionResult AddType()
        {
            int loggeduser = 0;
            if (Session["User"] != null)
            {
                loggeduser = App.Common.GetUserID().Value;
                int userole;
                foreach (Users usr in rm.GetReqUser())
                {
                    if (usr.UserID == loggeduser)
                    {
                        userole = usr.RoleID;
                        if (userole < 3)
                        {
                            return RedirectToAction("Index", "Index");
                        }
                    }
                }
            }
            return View();
        }
        [Auth]
        [HttpPost]
        public ActionResult AddType(RequestType model)
        {
            if (ModelState.IsValid)
            {
                if (model.RequestTypeTitle != null)
                {
                    ErrorsResults<RequestType> er = rm.AddType(model);

                    if (er.Errors.Count > 0)
                    {
                        er.Errors.ForEach(x => ModelState.AddModelError("", x));
                        return View(model);
                    }

                    return View();

                }

            }
            return View(model);
        }
    }
}

SUPPORTMVC.WEB/Views/AdminRequestExtensions/AddPriority.cshtml
@using SUPPORTMVC.BLL
@using SUPPORTMVC.ENTITIES.DBT
@model RequestPriority
@{
    ViewBag.Title = "AddPriority";
    Layout = "~/Views/Shared/_Layout.cshtml";

    RequestManager rm = new RequestManager();
    List<RequestPriority> rpl = rm.GetReqPrioList();
}
<div class="m-portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text col-md-12">
                    Talep Durumu Ekle
                </h3>
            </div>
        </div>
    </div>
    @if (ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
    {
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label m--font-bolder"></label>
                <div class="col-md-4">
                    <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-danger alert-dismissible fade show" role="alert" id="alertmsg">
                        <div class="m-alert__icon">
                            <i class="flaticon-exclamation-1"></i>
                            <span></span>
                        </div>
                        <div class="m-alert__text">
                            @Html.ValidationSummary(false)
                        </div>
                        <div class="m-alert__close">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    @using (Html.BeginForm("AddPriority", "AdminRequestExtensions", FormMethod.Post, new { @class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" }))
    {
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-1 col-form-label m--font-bolder">Öncelik Başlığı:</label>
                <div class="col-md-4">
                    <input class="form-control m-input m--font-boldest2" type="text" name="PriorityTitle" />
                </div>
                <label class="col-lg-1 col-form-label m--font-bolder">Öncelikler:</label>
                <div class="col-md-3">
                    <div class="m-demo">
                        <div class="m-demo__preview">
                            <ul class="m-nav">
                                @foreach (RequestPriority rp in rpl)
                                {
                                    <li class="m-nav__item">
                                        <span class="m-nav__link-text"><i class="fa fa-square"></i><span class="m--font-bolder m--icon-font-size-sm3"> @rp.PriorityTitle </span></span>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions ">
                    <div class="row">
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-info m--font-bolder" id="btnfirmakayit">Kaydet</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

SUPPORTMVC.WEB/Views/AdminRequestExtensions/AddStatus.cshtml
@using SUPPORTMVC.BLL
@using SUPPORTMVC.ENTITIES.DBT
@model RequestStatus
@{
    ViewBag.Title = "AddStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";

    RequestManager rm = new RequestManager();
    List<RequestStatus> rsl = rm.GetReqStatus();
}
<div class="m-portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text col-md-12">
                    Talep Durumu Ekle
                </h3>
            </div>
        </div>
    </div>
    @if (ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
    {
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label m--font-bolder"></label>
                <div class="col-md-4">
                    <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-danger alert-dismissible fade show" role="alert" id="alertmsg">
                        <div class="m-alert__icon">
                            <i class="flaticon-exclamation-1"></i>
                            <span></span>
                        </div>
                        <div class="m-alert__text">
                            @Html.ValidationSummary(false)
                        </div>
                        <div class="m-alert__close">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    @using (Html.BeginForm("AddStatus", "AdminRequestExtensions", FormMethod.Post, new {@class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" }))
    { 
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-1 col-form-label m--font-bolder">Durum Başlığı:</label>
                <div class="col-md-4">
                    <input class="form-control m-input m--font-boldest2" type="text" name="StatusTitle" />
                </div>
                <label class="col-lg-1 col-form-label m--font-bolder">Kayıtlı Durumlar:</label>
                <div class="col-md-3">
                    <div class="m-demo">
                        <div class="m-demo__preview">
                            <ul class="m-nav">
                                @foreach (RequestStatus rs in rsl)
                                {
                                    <li class="m-nav__item">
                                        <span class="m-nav__link-text"><i class="fa fa-square"></i><span class="m--font-bolder m--icon-font-size-sm3"> @rs.StatusTitle </span></span>
                                    </li>
                                    }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions ">
                    <div class="row">
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-info m--font-bolder" id="btnfirmakayit">Kaydet</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

SUPPORTMVC.WEB/Views/AdminRequestExtensions/AddType.cshtml
@using SUPPORTMVC.BLL
@using SUPPORTMVC.ENTITIES.DBT
@model RequestType
@{
    ViewBag.Title = "AddType";
    Layout = "~/Views/Shared/_Layout.cshtml";

    RequestManager rm = new RequestManager();
    List<RequestType> rtl = rm.GetReqTypeList();
}
<div class="m-portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text col-md-12">
                    Talep Durumu Ekle
                </h3>
            </div>
        </div>
    </div>
    @if (ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
    {
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label m--font-bolder"></label>
                <div class="col-md-4">
                    <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-danger alert-dismissible fade show" role="alert" id="alertmsg">
                        <div class="m-alert__icon">
                            <i class="flaticon-exclamation-1"></i>
                            <span></span>
                        </div>
                        <div class="m-alert__text">
                            @Html.ValidationSummary(false)
                        </div>
                        <div class="m-alert__close">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    @using (Html.BeginForm("AddType", "AdminRequestExtensions", FormMethod.Post, new { @class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" }))
    {
        <div class="m-portlet__body">
            <div class="form-group m-form__group row">
                <label class="col-lg-1 col-form-label m--font-bolder">Tür Başlığı:</label>
                <div class="col-md-4">
                    <input class="form-control m-input m--font-boldest2" type="text" name="RequestTypeTitle" />
                </div>
                <label class="col-lg-1 col-form-label m--font-bolder">Kayıtlı Türler:</label>
                <div class="col-md-3">
                    <div class="m-demo">
                        <div class="m-demo__preview">
                            <ul class="m-nav">
                                @foreach (RequestType rt in rtl)
                                {
                                    <li class="m-nav__item">
                                        <span class="m-nav__link-text"><i class="fa fa-square"></i><span class="m--font-bolder m--icon-font-size-sm3"> @rt.RequestTypeTitle </span></span>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions ">
                    <div class="row">
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-info m--font-bolder" id="btnfirmakayit">Kaydet</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>